const ethers = require("ethers");

exports.verifyphrase = async (req, res) => {
  try {
    const { mnemonic } = req.body;
    const isValidMnemonic = ethers.utils.isValidMnemonic(mnemonic);

    if (isValidMnemonic) {
      res.status(201).json({ valid: true });
    } else {
      res.status(201).json({ valid: false });
    }
  } catch (error) {
    console.error("Error verifying mnemonic:", error);
    res.status(500).json({ error: "Internal server error" });
  }
};

exports.getCoinList = async () => {
  const list = [
    {
      id: "bitcoin",
      name: "Bitcoin",
      symbol: "BTC",
      chainName: "Bitcoin",
      chainSymbol: "BTC",
      image: "https://assets.coingecko.com/coins/images/1/large/bitcoin.png",
    },

    //test net
    {
      id: "ethereum",
      chainId: 1,
      chainHex: "0x13881",
      chainName: "Mumbai",
      chainSymbol: "MUM",
      name: "Ethereum",
      symbol: "ETH",
      image: "https://assets.coingecko.com/coins/images/279/large/ethereum.png",
    },

    {
      id: "binancecoin",
      chainId: 56,
      chainIdHex: "0x61",
      chainName: "Bsc Testnet",
      chainSymbol: "BNB",
      symbol: "BNB",
      name: "Binance Smart Chain",
      image:
        "https://assets.coingecko.com/coins/images/825/large/binance-coin-logo.png",
    },

    {
      id: "ethereum",
      chainId: 1,
      chainHex: "0x1",
      chainName: "Ethereum",
      chainSymbol: "ETH",
      name: "Ethereum",
      symbol: "ETH",
      image: "https://assets.coingecko.com/coins/images/279/large/ethereum.png",
    },
    {
      id: "tether",
      chainId: 1,
      chainHex: "0x1",
      chainName: "Ethereum",
      chainSymbol: "ETH",
      name: "Tether",
      symbol: "USDT",
      image: "https://assets.coingecko.com/coins/images/325/large/tether.png",
    },
    {
      id: "usd-coin",
      chainId: 1,
      chainHex: "0x1",
      chainName: "Ethereum",
      chainSymbol: "ETH",
      name: "USD Coin",
      symbol: "USDC",
      image:
        "https://assets.coingecko.com/coins/images/6319/large/USD_Coin_icon.png",
    },
    {
      id: "wrapped-bitcoin",
      chainId: 1,
      chainHex: "0x1",
      chainName: "Ethereum",
      chainSymbol: "ETH",
      name: "Wrapped Bitcoin",
      symbol: "WBTC",
      image:
        "https://assets.coingecko.com/coins/images/7598/large/wrapped_bitcoin_wbtc.png",
    },
    // ... (continued for other coins)
    {
      id: "yearn-finance",
      chainId: 1,
      chainHex: "0x1",
      chainName: "Ethereum",
      chainSymbol: "ETH",
      name: "yearn.finance",
      symbol: "YFI",
      image:
        "https://assets.coingecko.com/coins/images/11849/large/yfi-192x192.png",
    },

    {
      id: "celsius",
      chainId: 1,
      chainHex: "0x1",
      chainName: "Ethereum",
      chainSymbol: "ETH",
      name: "Celsius",
      symbol: "CEL",
      image:
        "https://assets.coingecko.com/coins/images/3263/large/CEL_logo.png",
    },
    {
      id: "maker",
      chainId: 1,
      chainIdHex: "0x1",
      chainName: "Ethereum",
      chainSymbol: "ETH",
      symbol: "MKR",
      name: "Maker",
      image:
        "https://assets.coingecko.com/coins/images/1364/large/Mark_Maker.png",
    },
    {
      id: "compound",
      chainId: 1,
      chainIdHex: "0x1",
      chainName: "Ethereum",
      chainSymbol: "ETH",
      symbol: "COMP",
      name: "Compound",
      image: "https://assets.coingecko.com/coins/images/10775/large/COMP.png",
    },
    {
      id: "uniswap",
      chainId: 1,
      chainIdHex: "0x1",
      chainName: "Ethereum",
      chainSymbol: "ETH",
      symbol: "UNI",
      name: "Uniswap",
      image:
        "https://assets.coingecko.com/coins/images/12504/large/uniswap-uni.png",
    },
    {
      id: "aave",
      chainId: 1,
      chainIdHex: "0x1",
      chainName: "Ethereum",
      chainSymbol: "ETH",
      symbol: "AAVE",
      name: "Aave",
      image: "https://assets.coingecko.com/coins/images/12645/large/AAVE.png",
    },
    {
      id: "sushi",
      chainId: 1,
      chainIdHex: "0x1",
      chainName: "Ethereum",
      chainSymbol: "ETH",
      symbol: "SUSHI",
      name: "SushiSwap",
      image:
        "https://assets.coingecko.com/coins/images/12271/large/512x512_Logo_no_chop.png",
    },
    {
      id: "curve-dao-token",
      chainId: 1,
      chainIdHex: "0x1",
      chainName: "Ethereum",
      chainSymbol: "ETH",
      symbol: "CRV",
      name: "Curve DAO Token",
      image: "https://assets.coingecko.com/coins/images/12124/large/Curve.png",
    },
    {
      id: "synthetix-network-token",
      chainId: 1,
      chainIdHex: "0x1",
      chainName: "Ethereum",
      chainSymbol: "ETH",
      symbol: "SNX",
      name: "Synthetix Network Token",
      image: "https://assets.coingecko.com/coins/images/3406/large/SNX.png",
    },
    {
      id: "compound-governance-token",
      chainId: 1,
      chainIdHex: "0x1",
      chainName: "Ethereum",
      chainSymbol: "ETH",
      symbol: "COMP",
      name: "Compound Governance Token",
      image: "https://assets.coingecko.com/coins/images/10775/large/COMP.png",
    },
    {
      id: "yearn-finance-ii",
      chainId: 1,
      chainIdHex: "0x1",
      chainName: "Ethereum",
      chainSymbol: "ETH",
      symbol: "YFII",
      name: "Yearn.Finance II",
      image:
        "https://assets.coingecko.com/coins/images/11902/large/YFII-logo.78631676.png",
    },
    {
      id: "balancer",
      chainId: 1,
      chainIdHex: "0x1",
      chainName: "Ethereum",
      chainSymbol: "ETH",
      symbol: "BAL",
      name: "Balancer",
      image:
        "https://assets.coingecko.com/coins/images/11683/large/Balancer.png",
    },
    // ... (continuing for the remaining coins)

    //binance

    {
      id: "binancecoin",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "BNB",
      name: "Binance Coin",
      image:
        "https://assets.coingecko.com/coins/images/825/large/binance-coin-logo.png",
    },
    {
      id: "tether",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "USDT",
      name: "Tether",
      image: "https://assets.coingecko.com/coins/images/325/large/tether.png",
    },
    {
      id: "pancakeswap-token",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "CAKE",
      name: "PancakeSwap Token",
      image:
        "https://assets.coingecko.com/coins/images/12632/large/IMG_0440.PNG",
    },
    {
      id: "busd",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "BUSD",
      name: "Binance USD",
      image: "https://assets.coingecko.com/coins/images/9576/large/BUSD.png",
    },
    {
      id: "safemoon",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "SAFEMOON",
      name: "SafeMoon",
      image:
        "https://assets.coingecko.com/coins/images/14362/large/safemoon.png",
    },
    {
      id: "wbnb",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "WBNB",
      name: "Wrapped BNB",
      image:
        "https://assets.coingecko.com/coins/images/825/large/binance-coin-logo.png",
    },
    {
      id: "auto",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "AUTO",
      name: "Auto",
      image:
        "https://assets.coingecko.com/coins/images/13463/large/autofarm_icon_200x200.png",
    },
    {
      id: "safepal",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "SFP",
      name: "SafePal",
      image:
        "https://assets.coingecko.com/coins/images/13905/large/safepal.png",
    },
    {
      id: "apeswap-finance",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "BANANA",
      name: "ApeSwap Finance",
      image: "https://assets.coingecko.com/coins/images/14396/large/ape.png",
    },
    {
      id: "titan",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "TITAN",
      name: "Titan",
      image:
        "https://assets.coingecko.com/coins/images/14448/large/714ca92f5d9d6c717c7a9c90e3eabc603df115b2.png",
    },
    {
      id: "julswap",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "JULD",
      name: "JulSwap",
      image:
        "https://assets.coingecko.com/coins/images/15036/large/julswap.png",
    },
    {
      id: "dodoex",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "DODO",
      name: "DODOex",
      image:
        "https://assets.coingecko.com/coins/images/12651/large/dodo_logo.png",
    },
    {
      id: "vai",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "VAI",
      name: "Vai",
      image:
        "https://assets.coingecko.com/coins/images/14477/large/vai_logo.png",
    },
    {
      id: "soteria",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "WSOTE",
      name: "Soteria",
      image:
        "https://assets.coingecko.com/coins/images/14780/large/200x200.png",
    },
    {
      id: "helmet-insure",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "HELMET",
      name: "Helmet Insure",
      image:
        "https://assets.coingecko.com/coins/images/14378/large/helmet-insure-200x200.png",
    },
    {
      id: "world-token",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "WORLD",
      name: "World Token",
      image:
        "https://assets.coingecko.com/coins/images/15006/large/world-token-200x200.png",
    },
    {
      id: "anyswap-coin",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "ANY",
      name: "Anyswap Coin",
      image:
        "https://assets.coingecko.com/coins/images/12881/large/anyswap.jpg",
    },
    {
      id: "cheeseswap",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "CHS",
      name: "CheeseSwap",
      image:
        "https://assets.coingecko.com/coins/images/13761/large/cheeseswap.png",
    },
    {
      id: "watch-token",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "WATCH",
      name: "WATCH Token",
      image:
        "https://assets.coingecko.com/coins/images/15168/large/watch-token.png",
    },
    {
      id: "zg-bsc",
      chainId: 56,
      chainIdHex: "0x38",
      chainName: "Binance Smart Chain",
      chainSymbol: "BNB",
      symbol: "ZG",
      name: "Zero Gravity",
      image: "https://assets.coingecko.com/coins/images/16810/large/Logo.png",
    },

    //polygon

    {
      id: "matic-network",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "MATIC",
      name: "Polygon",
      image:
        "https://assets.coingecko.com/coins/images/4713/large/matic___polygon.jpg",
    },
    {
      id: "usd-coin",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "USDC",
      name: "USD Coin",
      image:
        "https://assets.coingecko.com/coins/images/6319/large/USD_Coin_icon.png",
    },
    {
      id: "wrapped-bitcoin",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "WBTC",
      name: "Wrapped Bitcoin",
      image:
        "https://assets.coingecko.com/coins/images/7598/large/wrapped_bitcoin_wbtc.png",
    },
    {
      id: "matic-aave-aave",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "AAVE",
      name: "Aave",
      image: "https://assets.coingecko.com/coins/images/12645/large/aave.png",
    },
    {
      id: "quick",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "QUICK",
      name: "QuickSwap",
      image: "https://assets.coingecko.com/coins/images/14155/large/quick.png",
    },
    {
      id: "sushi",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "SUSHI",
      name: "Sushi",
      image:
        "https://assets.coingecko.com/coins/images/12271/large/512x512_Logo_no_chop.png",
    },
    {
      id: "weth",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "WETH",
      name: "Wrapped Ether",
      image: "https://assets.coingecko.com/coins/images/2518/large/weth.png",
    },
    {
      id: "dai",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "DAI",
      name: "Dai",
      image:
        "https://assets.coingecko.com/coins/images/9956/large/dai-multi-collateral-mcd.png",
    },
    {
      id: "iron-usd",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "IRON",
      name: "Iron",
      image: "https://assets.coingecko.com/coins/images/14496/large/iron.png",
    },
    {
      id: "quickswap",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "QUICK",
      name: "QuickSwap",
      image: "https://assets.coingecko.com/coins/images/14155/large/quick.png",
    },
    {
      id: "aavegotchi",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "GHST",
      name: "Aavegotchi",
      image:
        "https://assets.coingecko.com/coins/images/12423/large/aavegotchi.jpg",
    },
    {
      id: "wazirx",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "WRX",
      name: "WazirX",
      image: "https://assets.coingecko.com/coins/images/10547/large/WazirX.png",
    },
    {
      id: "decentraland",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "MANA",
      name: "Decentraland",
      image:
        "https://assets.coingecko.com/coins/images/878/large/decentraland-mana.png",
    },
    {
      id: "curve-dao-token",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "CRV",
      name: "Curve DAO Token",
      image: "https://assets.coingecko.com/coins/images/12124/large/Curve.png",
    },
    {
      id: "matic-network",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "MATIC",
      name: "Polygon",
      image:
        "https://assets.coingecko.com/coins/images/4713/large/matic___polygon.jpg",
    },
    {
      id: "tether",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "USDT",
      name: "Tether",
      image: "https://assets.coingecko.com/coins/images/325/large/tether.png",
    },
    {
      id: "usd-coin",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "USDC",
      name: "USD Coin",
      image:
        "https://assets.coingecko.com/coins/images/6319/large/USD_Coin_icon.png",
    },
    {
      id: "wrapped-bitcoin",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "WBTC",
      name: "Wrapped Bitcoin",
      image:
        "https://assets.coingecko.com/coins/images/7598/large/wrapped_bitcoin_wbtc.png",
    },
    {
      id: "matic-aave-aave",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "AAVE",
      name: "Aave",
      image: "https://assets.coingecko.com/coins/images/12645/large/aave.png",
    },
    {
      id: "quick",
      chainId: 137,
      chainIdHex: "0x89",
      chainName: "Polygon",
      chainSymbol: "MATIC",
      symbol: "QUICK",
      name: "QuickSwap",
      image: "https://assets.coingecko.com/coins/images/14155/large/quick.png",
    },

    //avalanche
    {
      id: "avalanche-2",
      chainId: 43114,
      chainHex: "0xa86a",
      chainName: "Avalanche",
      chainSymbol: "AVAX",
      symbol: "AVAX",
      name: "Avalanche",
      image:
        "https://assets.coingecko.com/coins/images/12559/large/coin-round-red.png",
    },
    {
      id: "pangolin",
      chainId: 43114,
      chainHex: "0xa869",
      chainName: "Avalanche",
      chainSymbol: "AVAX",
      symbol: "PNG",
      name: "Pangolin",
      image:
        "https://assets.coingecko.com/coins/images/13414/large/Y6u3Tc8.png",
    },
    {
      id: "elk-finance",
      chainId: 43114,
      chainHex: "0xa868",
      chainName: "Avalanche",
      chainSymbol: "AVAX",
      symbol: "ELK",
      name: "Elk Finance",
      image:
        "https://assets.coingecko.com/coins/images/14184/large/Elk_Finance.png",
    },
    {
      id: "snowball",
      chainId: 43114,
      chainHex: "0xa867",
      chainName: "Avalanche",
      chainSymbol: "AVAX",
      symbol: "SNOB",
      name: "Snowball",
      image:
        "https://assets.coingecko.com/coins/images/14163/large/snob-small.png",
    },
    {
      id: "avalaunch",
      chainId: 43114,
      chainHex: "0xa866",
      chainName: "Avalanche",
      chainSymbol: "AVAX",
      symbol: "XAVA",
      name: "Avalaunch",
      image:
        "https://assets.coingecko.com/coins/images/14123/large/ava_round.png",
    },
    {
      id: "deerfi",
      chainId: 43114,
      chainHex: "0xa865",
      chainName: "Avalanche",
      chainSymbol: "AVAX",
      symbol: "DEER",
      name: "Deerfi",
      image: "https://assets.coingecko.com/coins/images/14469/large/deerfi.png",
    },
    {
      id: "pandaswap",
      chainId: 43114,
      chainHex: "0xa864",
      chainName: "Avalanche",
      chainSymbol: "AVAX",
      symbol: "PANDA",
      name: "PandaSwap",
      image:
        "https://assets.coingecko.com/coins/images/14207/large/PS%20Logo%20Green.png",
    },
    {
      id: "joe",
      chainId: 43114,
      chainHex: "0xa863",
      chainName: "Avalanche",
      chainSymbol: "AVAX",
      symbol: "JOE",
      name: "JOE",
      image:
        "https://assets.coingecko.com/coins/images/14283/large/joe-cropped.png",
    },
    {
      id: "vxv",
      chainId: 43114,
      chainHex: "0xa862",
      chainName: "Avalanche",
      chainSymbol: "AVAX",
      symbol: "VXV",
      name: "VXV",
      image:
        "https://assets.coingecko.com/coins/images/14134/large/vxv-logo.png",
    },
    {
      id: "frax",
      chainId: 43114,
      chainHex: "0xa861",
      chainName: "Avalanche",
      chainSymbol: "AVAX",
      symbol: "FRAX",
      name: "Frax",
      image:
        "https://assets.coingecko.com/coins/images/13410/large/frax_32_32.png",
    },
    {
      id: "tarot",
      chainId: 43114,
      chainHex: "0xa860",
      chainName: "Avalanche",
      chainSymbol: "AVAX",
      symbol: "TAROT",
      name: "Tarot",
      image: "https://assets.coingecko.com/coins/images/13972/large/logo.png",
    },
    {
      id: "nyanswop",
      chainId: 43114,
      chainHex: "0xa86f",
      chainName: "Avalanche",
      chainSymbol: "AVAX",
      symbol: "NYA",
      name: "Nyanswop",
      image:
        "https://assets.coingecko.com/coins/images/14703/large/nyanswop.png",
    },

    {
      id: "nyanswop",
      chainId: 43114,
      chainHex: "0xa86f",
      chainName: "Avalanche",
      chainSymbol: "AVAX",
      symbol: "NYA",
      name: "Nyanswop",
      image:
        "https://assets.coingecko.com/coins/images/14703/large/nyanswop.png",
    },

    {
      id: "galaxy-coin",
      chainId: 43114,
      chainHex: "0xa86d",
      chainName: "Avalanche",
      chainSymbol: "AVAX",
      symbol: "GALA",
      name: "Galaxy Coin",
      image:
        "https://assets.coingecko.com/coins/images/14853/large/gala-token-200x200.png",
    },
    {
      id: "mysterium",
      chainId: 43114,
      chainHex: "0xa86c",
      chainName: "Avalanche",
      chainSymbol: "AVAX",
      symbol: "MYST",
      name: "Mysterium",
      image:
        "https://assets.coingecko.com/coins/images/689/large/mysterium.png",
    },
    {
      id: "aavegotchi",
      chainId: 43114,
      chainHex: "0xa86b",
      chainName: "Avalanche",
      chainSymbol: "AVAX",
      symbol: "GHST",
      name: "Aavegotchi",
      image:
        "https://assets.coingecko.com/coins/images/12404/large/aavegotchi.jpg",
    },

    //fantom
    {
      id: "fantom",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "FTM",
      name: "Fantom",
      image: "https://assets.coingecko.com/coins/images/4001/large/Fantom.png",
    },
    {
      id: "wrapped-fantom",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "WFTM",
      name: "Wrapped Fantom",
      image: "https://assets.coingecko.com/coins/images/13469/large/ftm.png",
    },
    {
      id: "scream",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "SCR",
      name: "Scream",
      image: "https://assets.coingecko.com/coins/images/17971/large/scream.PNG",
    },
    {
      id: "spirit",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "SPIRIT",
      name: "Spirit",
      image: "https://assets.coingecko.com/coins/images/16984/large/spirit.png",
    },
    {
      id: "hyper-finance",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "HYFI",
      name: "Hyper Finance",
      image:
        "https://assets.coingecko.com/coins/images/14375/large/hyfi_logo.png",
    },
    {
      id: "spiritswap",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "SPIRIT",
      name: "SpiritSwap",
      image: "https://assets.coingecko.com/coins/images/14471/large/spirit.png",
    },
    {
      id: "fantom-token",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "FTM",
      name: "Fantom Token",
      image: "https://assets.coingecko.com/coins/images/4001/large/Fantom.png",
    },
    {
      id: "cream-2",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "CREAM",
      name: "Cream",
      image: "https://assets.coingecko.com/coins/images/11976/large/Cream.png",
    },
    {
      id: "fantom-operations",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "OPERATIONS",
      name: "Fantom Operations",
      image:
        "https://assets.coingecko.com/coins/images/19940/large/fantom-operations.png",
    },
    {
      id: "frankenstein",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "FRANK",
      name: "Frankenstein",
      image:
        "https://assets.coingecko.com/coins/images/16954/large/frankenstein.jpg",
    },
    {
      id: "beethovenx",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "BEETS",
      name: "BeethovenX",
      image: "https://assets.coingecko.com/coins/images/15581/large/beets.png",
    },
    {
      id: "golff",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "GOLFF",
      name: "Golff",
      image: "https://assets.coingecko.com/coins/images/16748/large/golff.png",
    },
    {
      id: "ghostswap",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "GHOST",
      name: "GhostSwap",
      image:
        "https://assets.coingecko.com/coins/images/16874/large/ghostswap.png",
    },
    {
      id: "spirit-moon",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "SPIRITMOON",
      name: "Spirit Moon",
      image:
        "https://assets.coingecko.com/coins/images/17911/large/spirit_moon.png",
    },
    {
      id: "scream-token",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "SCREAM",
      name: "Scream Token",
      image:
        "https://assets.coingecko.com/coins/images/17955/large/scream_token.png",
    },
    {
      id: "spooky-token",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "SPOOKY",
      name: "Spooky Token",
      image: "https://assets.coingecko.com/coins/images/17994/large/spooky.png",
    },
    {
      id: "fantom-daily",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "FTMD",
      name: "Fantom Daily",
      image: "https://assets.coingecko.com/coins/images/18142/large/ftmd.png",
    },
    {
      id: "vivid-token",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "VIVID",
      name: "Vivid Token",
      image:
        "https://assets.coingecko.com/coins/images/18383/large/vivid_logo.png",
    },
    {
      id: "rari-governance-token",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "RGT",
      name: "Rari Governance Token",
      image:
        "https://assets.coingecko.com/coins/images/18483/large/rgt_logo.png",
    },
    {
      id: "liquiddriver",
      chainId: 250,
      chainHex: "0xfa",
      chainName: "Fantom",
      chainSymbol: "FTM",
      symbol: "LIQUID",
      name: "LiquidDriver",
      image:
        "https://assets.coingecko.com/coins/images/18576/large/liquiddriver.png",
    },

    //crono
    {
      id: "cronos",
      chainId: 366,
      chainHex: "0x19",
      chainName: "Cronos",
      chainSymbol: "CRON",
      symbol: "CRON",
      name: "Cronos",
      image: "https://assets.coingecko.com/coins/images/18924/large/cronos.png",
    },
    {
      id: "cron-farm",
      chainId: 366,
      chainHex: "0x19",
      chainName: "Cronos",
      chainSymbol: "CRON",
      symbol: "CORN",
      name: "Cron Farm",
      image: "https://assets.coingecko.com/coins/images/19191/large/corn.png",
    },
    {
      id: "synapse",
      chainId: 366,
      chainHex: "0x19",
      chainName: "Cronos",
      chainSymbol: "CRON",
      symbol: "SYN",
      name: "Synapse",
      image:
        "https://assets.coingecko.com/coins/images/19288/large/synapse.png",
    },
    {
      id: "cron-cat",
      chainId: 366,
      chainHex: "0x19",
      chainName: "Cronos",
      chainSymbol: "CRON",
      symbol: "CAT",
      name: "Cron Cat",
      image:
        "https://assets.coingecko.com/coins/images/19375/large/cron_cat.png",
    },
    {
      id: "transcodium",
      chainId: 366,
      chainHex: "0x19",
      chainName: "Cronos",
      chainSymbol: "CRON",
      symbol: "TNS",
      name: "Transcodium",
      image:
        "https://assets.coingecko.com/coins/images/19484/large/transcodium.png",
    },
    {
      id: "open-cronos",
      chainId: 366,
      chainHex: "0x19",
      chainName: "Cronos",
      chainSymbol: "CRON",
      symbol: "CRONOS",
      name: "Open Cronos",
      image:
        "https://assets.coingecko.com/coins/images/19511/large/open_cronos.png",
    },
    {
      id: "cyrpto-taste",
      chainId: 366,
      chainHex: "0x19",
      chainName: "Cronos",
      chainSymbol: "CRON",
      symbol: "TT",
      name: "Cyrpto Taste",
      image:
        "https://assets.coingecko.com/coins/images/19645/large/crypto_taste.png",
    },
    {
      id: "leesadaisy",
      chainId: 366,
      chainHex: "0x19",
      chainName: "Cronos",
      chainSymbol: "CRON",
      symbol: "LEESA",
      name: "Leesa Daisy",
      image:
        "https://assets.coingecko.com/coins/images/19686/large/leesadaisy.png",
    },
    {
      id: "hazyswap",
      chainId: 366,
      chainHex: "0x19",
      chainName: "Cronos",
      chainSymbol: "CRON",
      symbol: "HAZY",
      name: "Hazyswap",
      image:
        "https://assets.coingecko.com/coins/images/19709/large/hazyswap.png",
    },
    {
      id: "firebird-finance",
      chainId: 366,
      chainHex: "0x19",
      chainName: "Cronos",
      chainSymbol: "CRON",
      symbol: "FYR",
      name: "Firebird Finance",
      image:
        "https://assets.coingecko.com/coins/images/19750/large/firebird_finance.png",
    },

    {
      id: "synapse",
      chainId: 366,
      chainHex: "0x19",
      chainName: "Cronos",
      chainSymbol: "CRON",
      symbol: "SYN",
      name: "Synapse",
      image:
        "https://assets.coingecko.com/coins/images/19288/large/synapse.png",
    },
    {
      id: "cron-cat",
      chainId: 366,
      chainHex: "0x19",
      chainName: "Cronos",
      chainSymbol: "CRON",
      symbol: "CAT",
      name: "Cron Cat",
      image:
        "https://assets.coingecko.com/coins/images/19375/large/cron_cat.png",
    },
    {
      id: "transcodium",
      chainId: 366,
      chainHex: "0x19",
      chainName: "Cronos",
      chainSymbol: "CRON",
      symbol: "TNS",
      name: "Transcodium",
      image:
        "https://assets.coingecko.com/coins/images/19484/large/transcodium.png",
    },
    {
      id: "open-cronos",
      chainId: 366,
      chainHex: "0x19",
      chainName: "Cronos",
      chainSymbol: "CRON",
      symbol: "CRONOS",
      name: "Open Cronos",
      image:
        "https://assets.coingecko.com/coins/images/19511/large/open_cronos.png",
    },
    {
      id: "cyrpto-taste",
      chainId: 366,
      chainHex: "0x19",
      chainName: "Cronos",
      chainSymbol: "CRON",
      symbol: "TT",
      name: "Cyrpto Taste",
      image:
        "https://assets.coingecko.com/coins/images/19645/large/crypto_taste.png",
    },
    {
      id: "leesadaisy",
      chainId: 366,
      chainHex: "0x19",
      chainName: "Cronos",
      chainSymbol: "CRON",
      symbol: "LEESA",
      name: "Leesa Daisy",
      image:
        "https://assets.coingecko.com/coins/images/19686/large/leesadaisy.png",
    },
    {
      id: "hazyswap",
      chainId: 366,
      chainHex: "0x19",
      chainName: "Cronos",
      chainSymbol: "CRON",
      symbol: "HAZY",
      name: "Hazyswap",
      image:
        "https://assets.coingecko.com/coins/images/19709/large/hazyswap.png",
    },
    {
      id: "firebird-finance",
      chainId: 366,
      chainHex: "0x19",
      chainName: "Cronos",
      chainSymbol: "CRON",
      symbol: "FYR",
      name: "Firebird Finance",
      image:
        "https://assets.coingecko.com/coins/images/19750/large/firebird_finance.png",
    },

    {
      id: "ethereum",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "ETH",
      name: "Ethereum",
      image: "https://assets.coingecko.com/coins/images/279/large/ethereum.png",
    },
    {
      id: "tether",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "USDT",
      name: "Tether",
      image: "https://assets.coingecko.com/coins/images/325/large/tether.png",
    },
    {
      id: "usd-coin",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "USDC",
      name: "USD Coin",
      image:
        "https://assets.coingecko.com/coins/images/6319/large/USD_Coin_icon.png",
    },
    {
      id: "dai",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "DAI",
      name: "Dai",
      image:
        "https://assets.coingecko.com/coins/images/9956/large/dai-multi-collateral-mcd.png",
    },
    {
      id: "aave",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "AAVE",
      name: "Aave",
      image: "https://assets.coingecko.com/coins/images/12645/large/AAVE.png",
    },
    {
      id: "chainlink",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "LINK",
      name: "Chainlink",
      image:
        "https://assets.coingecko.com/coins/images/877/large/chainlink-new-logo.png",
    },
    {
      id: "sushi",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "SUSHI",
      name: "SushiSwap",
      image:
        "https://assets.coingecko.com/coins/images/12271/large/sushiSwap.jpg",
    },
    {
      id: "uniswap",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "UNI",
      name: "Uniswap",
      image:
        "https://assets.coingecko.com/coins/images/12504/large/uniswap-uni.png",
    },
    {
      id: "curve-dao-token",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "CRV",
      name: "Curve DAO Token",
      image: "https://assets.coingecko.com/coins/images/12124/large/Curve.png",
    },
    {
      id: "wrapped-bitcoin",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "WBTC",
      name: "Wrapped Bitcoin",
      image:
        "https://assets.coingecko.com/coins/images/7598/large/wrapped_bitcoin_wbtc.png",
    },

    {
      id: "aavegotchi",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "GHST",
      name: "Aavegotchi",
      image:
        "https://assets.coingecko.com/coins/images/12407/large/aavegotchi.jpg",
    },
    {
      id: "badger-dao",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "BADGER",
      name: "Badger DAO",
      image:
        "https://assets.coingecko.com/coins/images/14503/large/badger-dao.png",
    },
    {
      id: "frax",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "FRAX",
      name: "Frax",
      image: "https://assets.coingecko.com/coins/images/13341/large/frax.png",
    },
    {
      id: "renbtc",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "RENBTC",
      name: "renBTC",
      image: "https://assets.coingecko.com/coins/images/11370/large/RENBTC.png",
    },
    {
      id: "pickle-finance",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "PICKLE",
      name: "Pickle Finance",
      image:
        "https://assets.coingecko.com/coins/images/11835/large/pickle_finance_logo.jpg",
    },
    {
      id: "wrapped-ether",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "WETH",
      name: "Wrapped Ether",
      image: "https://assets.coingecko.com/coins/images/2518/large/weth.png",
    },
    {
      id: "shiba-inu",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "SHIB",
      name: "Shiba Inu",
      image: "https://assets.coingecko.com/coins/images/11939/large/shiba.png",
    },
    {
      id: "mimatic",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "MATIC",
      name: "Polygon",
      image:
        "https://assets.coingecko.com/coins/images/4713/large/matic___polygon.jpg",
    },
    {
      id: "powerpool",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "CVP",
      name: "PowerPool",
      image:
        "https://assets.coingecko.com/coins/images/12389/large/powerpool.png",
    },
    {
      id: "fei-protocol",
      chainId: 42161,
      chainHex: "0xa4b1",
      chainName: "Arbitrum",
      chainSymbol: "ARB",
      symbol: "FEI",
      name: "Fei Protocol",
      image: "https://assets.coingecko.com/coins/images/14570/large/fei.png",
    },
  ];

  return list;
};
